Repository kstroevsky/bindfly.js, pull requests merged in 2022-12, with the labels that each got.

#2 Routing
  package.json
  src/App.css
  src/App.js
  src/DropDownContent/DropDownContent.jsx
  src/DropDownContent/DropDownContentItem.jsx
  src/components/Animation.js
  src/components/LinkItem.jsx
  src/components/ToggleButton.jsx
  src/components/canvas/animations/Particles/index.js
  src/components/layout.jsx
  src/hooks/useCanvas.js
  src/hooks/useLongPressHandler.js
  src/index.js
  src/properties.json
Labels: enhancement, good first issue

#6 bug/performance
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/DropDownContent/DropDownContent.jsx
  src/DropDownContent/DropDownContentItem.jsx
  src/components/Animation.js
  src/components/Animation/index.js
  src/components/Canvas/index.jsx
  src/components/Context/index.jsx
  src/components/DropdownContent/index.jsx
  src/components/DropdownItem/index.jsx
  src/components/LinkItem.jsx
  src/components/NavLinkItem/index.jsx
  src/components/PageLayout/index.jsx
  src/components/PageSidebar/index.jsx
  src/components/ToggleButton/index.jsx
  src/components/layout.jsx
  src/hooks/index.js
  src/hooks/useCanvas.js
  src/hooks/useForceUpdate.js
  src/hooks/useListenersEffect.js
  src/hooks/useLongPress.js
  src/hooks/useLongPressHandler.js
  src/hooks/useMediaQuery.js
  src/index.js
  src/properties.json
  src/router/index.jsx
  src/shared/2d/animations/FlyingLines/index.js
  src/shared/2d/templates/FlyingPoints/index.js
  src/shared/HOF/index.js
  src/shared/constants/index.js
  src/shared/utils/index.js
  src/shared/webAPI/web-workers/canvasWorker.js
  src/utils/index.js
  src/webAPI/workers/canvasWorker.js
Labels: bug, enhancement

#19 Loader
  package.json
  src/App.tsx
  src/components/Animation/index.tsx
  src/components/Loader/index.tsx
  src/components/Loader/styles.css
  src/components/LoaderTiles/index.tsx
  src/components/PageLayout/index.tsx
  src/hooks/useCanvas.ts
  src/properties.json
  src/router/index.tsx
  src/shared/types/index.ts
  src/shared/utils/index.ts
  src/shared/webAPI/web-workers/canvasWorker.js
  tsconfig.json
Labels: enhancement

#22 Clipboard animation config
  src/App.css
  src/assets/copy-icon.svg
  src/components/DropdownContent/index.tsx
  src/components/DropdownItem/index.tsx
  src/declaration.d.ts
  src/shared/constants/index.js
Labels: enhancement

#21 Update project setup
  .babelrc
  .gitignore
  package.json
  public/index.html
  src/App.css
  src/App.tsx
  src/assets/copyIcon.svg
  src/components/Animation/index.tsx
  src/components/Canvas/index.tsx
  src/components/Context/index.tsx
  src/components/DropdownContent/index.tsx
  src/components/DropdownItem/index.tsx
  src/components/Loader/index.tsx
  src/components/Loader/styles.css
  src/components/LoaderTiles/index.tsx
  src/components/NavLinkItem/index.tsx
  src/components/PageLayout/index.tsx
  src/components/PageSidebar/index.tsx
  src/components/ToggleButton/index.tsx
  src/declaration.d.ts
  src/hooks/index.ts
  src/hooks/useCanvas.ts
  src/hooks/useForceUpdate.ts
  src/hooks/useListenersEffect.ts
  src/hooks/useLongPress.ts
  src/hooks/useMediaQuery.ts
  src/index.css
  src/index.tsx
  src/properties.json
  src/reportWebVitals.js
  src/router/index.tsx
  src/shared/2d/animations/FlyingLines/index.js
  src/shared/2d/animations/abstract/canvas.ts
  src/shared/2d/templates/FlyingPoints/index.js
  src/shared/HOF/index.ts
  src/shared/WebApi/web-workers/canvas-worker.ts
  src/shared/constants/index.js
  src/shared/types/index.ts
  src/shared/utils/index.ts
  src/shared/webAPI/web-workers/canvasWorker.js
  tsconfig.json
  webpack.config.js
Labels: enhancement
